name = "Coalescent"
uuid = "7af52d38-510f-42b9-ba0a-b0cde7e92322"
authors = ["Erik Volz"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
